name: Publish to Hex
run-name: Publish to Hex on release

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.18-otp-27
          otp-version: otp-27

      - name: Fetch dependencies
        run: |
          mix deps.get

      - name: Publish to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix hex.publish --yes
